# github action to build and do artifact deployment from main branch
name: build artifact and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build
